Repository nasa-jpl/explorer-1, pull requests merged in 2022-02, with the labels that each got.

#140 Remove prerelease overrides for Release Drafter
  .github/workflows/update-release-draft.yml
Labels: maintenance, patch

#142 Issue templates: fixing labels in "Feature request" template
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: bug, maintenance, patch

#144 Docs: Fixing the link to the Explorer 1 readme
  storybook/stories/_docs/gettingstarted_developer.stories.mdx
Labels: bug, storybook, patch

#165 Update Tailwind config to not activate dark mode based on user's OS-level setting
  tailwind.config.js
Labels: bug
