Repository nasa-jpl/explorer-1, pull requests merged in 2022-03, with the labels that each got.

#161 Adding responsiveness to BlockIframeEmbed
  dist/css/explorer-1.min.css
  src/scss/_components.scss
  src/scss/components/_BaseIframe.scss
  storybook/stories/components/BaseIframe/BaseIframe.js
  storybook/stories/components/BaseIframe/BaseIframe.stories.js
  storybook/stories/components/BlockIframeEmbed/BlockIframeEmbed.js
  storybook/stories/components/BlockIframeEmbed/BlockIframeEmbed.stories.js
Labels: enhancement, storybook, minor, feature

#179 Bump @storybook (6.4.19) and eslint-plugin-storybook (0.5.7)
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: storybook, maintenance, patch, dependencies

#173 Improvements to BlockLinkCard and BlockLinkTile
  storybook/stories/components/BlockLinkCard/BlockLinkCard.js
  storybook/stories/components/BlockLinkCard/BlockLinkCard.stories.js
  storybook/stories/components/BlockLinkCarousel/BlockLinkCarousel.js
  storybook/stories/components/BlockLinkTile/BlockLinkTile.js
  storybook/stories/components/BlockLinkTile/BlockLinkTile.stories.js
Labels: enhancement, storybook, minor, feature

#186 Add nvmrc, Bump actions/checkout and actions/setup-node to v3
  .github/workflows/build-deploy-storybook.yml
  .github/workflows/lint.yml
  .nvmrc
  package.json
Labels: maintenance, patch

#182 Updating caniuse-lite and rebuilding dist
  dist/css/explorer-1.min.css
  package-lock.json
Labels: maintenance, minor

#188 Revert prettier to v2.5.1 to fix Storybook HTML addon
  .pre-commit-config.yaml
  package-lock.json
  package.json
Labels: bug, storybook, patch, fix

#193 Add LICENSE file and terms for contributing
  CONTRIBUTING.md
  LICENSE
Labels: maintenance, skip-changelog

#174 Adding docs on how to test the npm package locally
  CONTRIBUTING.md
Labels: documentation, patch
