Repository nasa-jpl/explorer-1, pull requests merged in 2024-09, with the labels that each got.

#588 fixes from feedback on edu events and news listing pages
  packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue
  packages/vue/src/components/BlockLinkCardList/BlockLinkCardList.vue
  packages/vue/src/components/CalendarChip/CalendarChip.vue
  packages/vue/src/components/Icons/IconCalendar.vue
  packages/vue/src/components/SearchResultCard/SearchResultCard.vue
  packages/vue/src/components/SearchResultGridItem/SearchResultGridItem.vue
  packages/vue/src/components/SearchResultsList/SearchResultsList.vue
  packages/vue/src/utils/mixins.ts
Labels: bug, patch

#589 feature: edu resource library index page
  packages/common/src/scss/_grid.scss
  packages/vue/src/components/BaseCarousel/BaseCarousel.vue
  packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue
  packages/vue/src/components/HeroListingIndex/HeroListingIndex.stories.js
  packages/vue/src/components/HeroListingIndex/HeroListingIndex.vue
  packages/vue/src/components/HeroMedium/HeroMedium.vue
  packages/vue/src/components/MetadataEduResource/MetadataEduResource.vue
  packages/vue/src/components/MetadataEvent/MetadataEvent.stories.js
  packages/vue/src/components/MetadataEvent/MetadataEvent.vue
  packages/vue/src/components/NavDesktop/NavDesktop.vue
  packages/vue/src/components/NavDesktopEdu/NavDesktopEdu.vue
  packages/vue/src/components/NavMobile/NavMobile.vue
  packages/vue/src/components/NewsDetailMediaContact/NewsDetailMediaContact.vue
  packages/vue/src/components/SearchFilterGroup/SearchFilterGroup.vue
  packages/vue/src/components/SearchResultCard/SearchResultCard.vue
  packages/vue/src/components/SearchResultGridItem/SearchResultGridItem.vue
  packages/vue/src/components/SearchResultsList/SearchResultsList.vue
  packages/vue/src/interfaces.ts
  packages/vue/src/templates/www/PageTimeline/PageTimeline.vue
  packages/vue/src/utils/mixins.ts
Labels: feature

#594 fix: edu resource multimedia and gallery templates
  .github/workflows/storybook.yml
  packages/common/src/scss/components/_BlockText.scss
  packages/vue/src/components/BaseImageCaption/BaseImageCaption.vue
  packages/vue/src/components/BlockImage/BlockImageFullBleed.vue
  packages/vue/src/components/BlockImage/BlockImageStandard.vue
  packages/vue/src/components/BlockImageComparison/BlockImageComparison.vue
  packages/vue/src/components/BlockVideo/BlockVideo.vue
  packages/vue/src/components/BlockVideoEmbed/BlockVideoEmbed.vue
  packages/vue/src/components/DetailHeadline/DetailHeadline.vue
  packages/vue/src/templates/edu/PageEduGalleryDetail/PageEduGalleryDetail.stories.js
  packages/vue/src/templates/edu/PageEduGalleryDetail/PageEduGalleryDetail.vue
  packages/vue/src/templates/edu/PageEduMultimediaDetail/PageEduMultimediaDetail.vue
Labels: bug

#596 fix: removing `/home/` prefix from BaseLink
  packages/vue/src/components/BaseLink/BaseLink.vue
Labels: bug

#597 fix: replace vue-observe-visibility with vue3-observe-visibility
  apps/vue-storybook/.storybook/preview.ts
  apps/vue-storybook/package.json
  packages/vue/package.json
  packages/vue/src/components/MissionDetailAbout/MissionDetailAbout.vue
  packages/vue/src/components/MissionDetailHighlights/MissionDetailHighlights.vue
  packages/vue/src/components/TopicDetailMore/TopicDetailMoreVisibility.vue
  pnpm-lock.yaml
Labels: bug, patch, feature parity

#598 various www-frontend parity fixes
  packages/vue/lib/main.ts
  packages/vue/src/components/BaseButton/BaseButton.vue
  packages/vue/src/components/BlockRelatedLinks/BlockRelatedLinks.vue
  packages/vue/src/components/BlockRelatedLinks/RelatedLink.vue
  packages/vue/src/components/BlockStreamfield/BlockStreamfield.vue
  packages/vue/src/components/BlockTwitterEmbed/BlockTwitterEmbed.stories.js
  packages/vue/src/components/BlockTwitterEmbed/BlockTwitterEmbed.vue
  packages/vue/src/components/HeroMedium/HeroMedium.vue
  packages/vue/src/components/HomepageCarouselItem/HomepageCarouselItem.vue
  packages/vue/src/components/NavSearchForm/NavSearchForm.vue
  packages/vue/src/components/SwimlaneCTA/SwimlaneCTA.vue
  packages/vue/src/components/TopicDetailMissionCarouselItem/TopicDetailMissionCarouselItem.vue
Labels: bug, feature parity

#600 fixes: Lesson Template and ClientOnly
  apps/vue-storybook/.storybook/_mock-components.js
  packages/vue/package.json
  packages/vue/src/components/BlockImageComparison/BlockImageComparison.vue
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue
  packages/vue/src/templates/edu/PageEduLesson/PageEduLessonSection.vue
  pnpm-lock.yaml
Labels: bug

#601 fixing headings in edu lesson jump menus, adding generateHash
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.stories.js
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue
  packages/vue/src/utils/generateHash.ts
Labels: bug

#602 fixing /home/ prefix, Search filter behavior tweaks
  packages/vue/src/components/BaseButton/BaseButton.vue
  packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue
  packages/vue/src/components/SearchFilterGroup/SearchFilterGroup.vue
  packages/vue/src/components/SearchResultCard/SearchResultCard.vue
  packages/vue/src/components/SearchResultGridItem/SearchResultGridItem.vue
  packages/vue/src/components/SearchResultsList/SearchResultsList.vue
  packages/vue/src/interfaces.ts
Labels: bug

#604 fixes setting both href and to in BaseButton's NuxtLink
  packages/vue/src/components/BaseButton/BaseButton.vue
Labels: bug

#605 Fix/vue-v0.2.49
  packages/vue/src/components/HomepageMissionsCarousel/HomepageMissionsCarousel.vue
  packages/vue/src/components/HomepageMissionsCarousel/HomepageMissionsCarouselItem.vue
  packages/vue/src/templates/PageImageDetail/PageImageDetail.vue
  packages/vue/src/templates/www/PageCuratedGallery/PageCuratedGallery.vue
  packages/vue/src/templates/www/PageHomepage/PageHomepage.vue
Labels: bug

#608 fix: Gallery Detail Page and BlockTeaser
  packages/vue/src/components/BlockTeaser/BlockTeaser.vue
  packages/vue/src/templates/edu/PageEduGalleryDetail/PageEduGalleryDetail.vue
Labels: bug, patch

#610 fix: fixing standards headings and math standards in EDU Lesson template
  packages/vue/src/components/MetaPanel/MetaPanel.vue
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.stories.js
Labels: bug

#612 fixing date metadata in edu event search results
  packages/vue/src/components/BlockLinkCard/BlockLinkCard.stories.js
  packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue
  packages/vue/src/components/MetadataEduResource/MetadataEduResource.vue
  packages/vue/src/components/MetadataEvent/MetadataEvent.vue
  packages/vue/src/components/SearchFilterGroup/SearchFilterGroup.vue
  packages/vue/src/components/SearchResultCard/SearchResultCard.stories.js
  packages/vue/src/components/SearchResultsList/SearchResultsList.vue
Labels: bug

#613 feature: making hero configuration the same between main EDU resources
  apps/vue-storybook/.storybook/preview.ts
  packages/vue/src/components/HeroMedia/HeroMedia.vue
  packages/vue/src/interfaces.ts
  packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.stories.js
  packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.vue
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.stories.js
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue
  packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProject.stories.js
  packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProject.vue
  packages/vue/src/templates/edu/PageEduTeachableMoment/PageEduTeachableMoment.stories.js
  packages/vue/src/templates/edu/PageEduTeachableMoment/PageEduTeachableMoment.vue
Labels: bug

#615 Fix/edu student project page
  packages/vue/src/components/BaseImage/BaseImage.vue
  packages/vue/src/components/BlockHeading/BlockHeading.vue
  packages/vue/src/components/BlockIframeEmbed/BlockIframeEmbed.vue
  packages/vue/src/components/BlockVideoEmbed/BlockVideoEmbed.vue
  packages/vue/src/components/HeroMedium/HeroMedium.vue
  packages/vue/src/components/MetaPanel/MetaPanel.vue
  packages/vue/src/components/NavJumpMenu/NavJumpMenu.vue
  packages/vue/src/components/NavJumpMenu/NavJumpMenuContent.vue
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue
  packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProject.vue
  packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProjectSection.vue
Labels: bug

#614 adding EDU Home page template
  packages/vue/src/components/SearchInput/SearchInput.vue
  packages/vue/src/templates/edu/PageEduHome/PageEduHome.stories.js
  packages/vue/src/templates/edu/PageEduHome/PageEduHome.vue
Labels: feature

#616 Feature/217 richtext image support
  packages/common/src/scss/components/_BlockText.scss
  packages/vue/src/components/BlockText/BlockText.stories.js
Labels: feature

#617 feature: edu resource subjects accordion filter group
  packages/vue/src/components/SearchFilterGroup/SearchFilterGroup.stories.js
  packages/vue/src/components/SearchFilterGroup/SearchFilterGroup.vue
  packages/vue/src/components/SearchFilterGroupAccordionItem/SearchFilterGroupAccordionItem.vue
  packages/vue/src/interfaces.ts
  packages/vue/src/templates/PageImageDetail/PageImageDetail.vue
Labels: feature

#618 fix: use of .sort() in Podcast templates
  packages/vue/src/components/PodcastSeriesCarousel/PodcastSeriesCarousel.vue
  packages/vue/src/templates/PageAudioDetail/PageAudioDetail.vue
  packages/vue/src/templates/PageImageDetail/PageImageDetail.vue
  packages/vue/src/templates/www/PagePodcast/PagePodcast.vue
  packages/vue/tsconfig.json
Labels: bug

#619 removing domain from search results urls to ensure router links
  packages/vue/src/components/SearchResultsList/SearchResultsList.vue
Labels: bug

#620 fix: student projects template feedback
  packages/vue/src/components/BlockHeading/BlockHeading.vue
  packages/vue/src/components/NavMobile/NavMobile.vue
  packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.vue
  packages/vue/src/templates/edu/PageEduGalleryDetail/PageEduGalleryDetail.vue
  packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProject.vue
  packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProjectSection.vue
Labels: bug, patch

#622 fix: Student Projects feedback and accordions
  packages/common/src/scss/components/_BlockText.scss
  packages/vue/src/components/BaseAccordionItem/BaseAccordionItem.vue
  packages/vue/src/components/SearchFilterGroup/SearchFilterGroup.vue
  packages/vue/src/components/SearchFilterGroupAccordionItem/SearchFilterGroupAccordionItem.vue
  packages/vue/src/components/SearchResultsList/SearchResultsList.vue
  packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProject.vue
Labels: bug

#623 hiding git sha in footer
  packages/vue/src/components/TheFooter/TheFooter.vue
Labels: maintenance

#624 fix: using FetchAsteroidWatchWidget
  apps/vue-storybook/.storybook/_mock-components.js
  packages/vue/src/templates/www/PageAsteroidWatchContent/PageAsteroidWatchContent.vue
Labels: bug

#625 fixing border in NavSecondary
  packages/vue/src/components/NavSecondary/NavSecondary.vue
Labels: bug

#626 fix: anchor links in mobile nav, long menus in Jump Nav
  packages/vue/src/components/BlockHeading/BlockHeading.vue
  packages/vue/src/components/NavJumpMenu/NavJumpMenu.stories.js
  packages/vue/src/components/NavJumpMenu/NavJumpMenu.vue
  packages/vue/src/components/NavSecondary/NavSecondaryDropdownContent.vue
Labels: bug, patch

#627 fix: rich table block
  packages/common/src/scss/_components.scss
  packages/common/src/scss/components/_BlockTable.scss
  packages/vue/lib/main.ts
  packages/vue/src/components/BlockRichTable/BlockRichTable.stories.js
  packages/vue/src/components/BlockRichTable/BlockRichTable.vue
  packages/vue/src/components/BlockStreamfield/BlockStreamfield.stories.js
  packages/vue/src/components/BlockStreamfield/BlockStreamfield.vue
  packages/vue/src/components/BlockTable/BlockTable.stories.js
  packages/vue/src/components/BlockTable/BlockTable.vue
  packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProject.stories.js
  packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProjectSection.vue
Labels: bug, patch

#628 fix: adjustments to floating images and unordered list markers
  packages/common/src/scss/components/_BlockKeyPoints.scss
  packages/common/src/scss/components/_BlockText.scss
  packages/vue/src/components/BlockKeyPoints/BlockKeyPoints.vue
  packages/vue/src/components/BlockText/BlockText.stories.js
  packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.vue
  packages/vue/src/templates/edu/PageEduGalleryDetail/PageEduGalleryDetail.vue
  packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProject.stories.js
  packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProject.vue
  packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProjectSection.vue
Labels: bug

#632 fixing edu path in NavSearchForm
  packages/vue/src/components/NavSearchForm/NavSearchForm.vue
Labels: bug

#633 fix: EDU BlockRichTable adjustments
  packages/common/src/scss/components/_BlockRichTable.scss
  packages/vue/src/components/BlockRichTable/BlockRichTable.stories.js
  packages/vue/src/components/BlockRichTable/BlockRichTable.vue
Labels: bug, patch

#634 Feature/edu collections block link card
  packages/vue/src/components/BlockLinkCard/BlockLinkCard.stories.js
  packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue
  packages/vue/src/components/BlockLinkCard/BlockLinkCardCollectionLg.vue
  packages/vue/src/components/MetadataEduResource/MetadataEduResource.vue
  packages/vue/src/components/SearchResultCard/SearchResultCard.vue
  packages/vue/src/components/SearchResultGridItem/SearchResultGridItem.vue
Labels: feature

#635 fix: listing metadata for EDU News and External Links
  packages/vue/src/components/BlockLinkCard/BlockLinkCard.stories.js
  packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue
  packages/vue/src/constants.ts
Labels: bug

#636 fix: markup for table caption
  packages/common/src/scss/components/_BlockRichTable.scss
  packages/vue/src/components/BlockRichTable/BlockRichTable.vue
  packages/vue/src/components/BlockStreamfield/BlockStreamfield.stories.js
Labels: bug

#637 fix: full bleed adjustments
  packages/vue/src/components/BlockCardGrid/BlockCardGrid.stories.js
  packages/vue/src/components/BlockCardGrid/BlockCardGrid.vue
  packages/vue/src/components/BlockImage/BlockImageFullBleed.vue
  packages/vue/src/components/HeroMedia/HeroMedia.vue
  packages/vue/src/components/NavDesktopEdu/NavDesktopEdu.vue
Labels: bug, patch

#639 fix: www homepage background gradient
  packages/vue/src/components/HomepageCarouselItem/HomepageCarouselItem.vue
Labels: bug, patch

#640 Fix/edu search placeholder text
  packages/vue/src/components/NavDesktopEdu/NavDesktopEdu.vue
  packages/vue/src/components/NavMobile/NavMobile.vue
  packages/vue/src/components/NavSearchForm/NavSearchForm.vue
Labels: bug

#641 fix: www homepage carousel tabbed navigation
  packages/vue/src/components/HomepageCarousel/HomepageCarousel.stories.js
  packages/vue/src/components/HomepageCarousel/HomepageCarousel.vue
  packages/vue/src/components/HomepageCarouselItem/HomepageCarouselItem.vue
Labels: bug

#642 fix: ensuring hero media is full-width
  packages/vue/src/components/HeroMedia/HeroMedia.vue
Labels: bug

#643 fixing rich text media in student project steps
  packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProjectSection.vue
Labels: bug

#644 EDU: adjusting height of accordion filter groups to match non-accordions
  packages/vue/src/components/SearchFilterGroupAccordionItem/SearchFilterGroupAccordionItem.vue
Labels: bug

#646 fix: rich text media on Student Projects
  packages/vue/src/templates/edu/PageEduStudentProject/PageEduStudentProjectSection.vue
Labels: bug
