Repository nasa-jpl/explorer-1, pull requests merged in 2024-08, with the labels that each got.

#530 Feature: BlockCardGrid
  apps/vue-storybook/.percy.yml
  apps/vue-storybook/.storybook/preview.ts
  apps/vue-storybook/package.json
  package.json
  packages/vue/lib/main.ts
  packages/vue/package.json
  packages/vue/src/components/BlockCardGrid/BlockCardGrid.stories.js
  packages/vue/src/components/BlockCardGrid/BlockCardGrid.vue
  packages/vue/src/components/BlockCardGridItem/BlockCardGridItem.stories.js
  packages/vue/src/components/BlockCardGridItem/BlockCardGridItem.vue
  packages/vue/src/components/BlockCardGridItem/BlockCardGridItemElement.vue
  packages/vue/src/components/BlockCardGroup/BlockCardGroup.vue
  packages/vue/src/components/BlockCircleImageCard/BlockCircleImageCard.stories.js
  packages/vue/src/components/BlockLinkCard/BlockLinkCard.stories.js
  packages/vue/src/components/BlockLinkTile/BlockLinkTile.stories.js
  packages/vue/src/components/BlockListCards/BlockListCards.stories.js
  packages/vue/src/components/BlockStreamfield/BlockStreamfield.stories.js
  packages/vue/src/components/BlockStreamfield/BlockStreamfield.vue
  packages/vue/src/components/LayoutHelper/LayoutHelper.vue
  packages/vue/src/docs/overviews/blocks.docs.mdx.disabled
  packages/vue/src/docs/overviews/cards.docs.mdx
  packages/vue/src/interfaces.ts
  packages/vue/src/templates/www/PageRoboticsDetail/PageRoboticsDetail.stories.js
  packages/vue/src/templates/www/PageRoboticsDetail/PageRoboticsDetail.vue
Labels: patch, feature

#531 Adds readTime to EDU News, EDU explainer articles, and WWW news
  package.json
  packages/vue/package.json
  packages/vue/src/components/DetailHeadline/DetailHeadline.stories.js
  packages/vue/src/components/DetailHeadline/DetailHeadline.vue
  packages/vue/src/templates/PageNewsDetail/PageNewsDetail.stories.js
  packages/vue/src/templates/PageNewsDetail/PageNewsDetail.vue
  packages/vue/src/templates/edu/PageEduNewsDetail/PageEduNewsDetail.stories.js
  packages/vue/src/templates/edu/PageEduNewsDetail/PageEduNewsDetail.vue
  packages/vue/src/templates/edu/PageEduResourceArticle/PageEduResourceArticle.stories.js
  packages/vue/src/templates/edu/PageEduResourceArticle/PageEduResourceArticle.vue
Labels: feature

#534 fix: Explainer Articles
  packages/vue/src/components/BaseTag/BaseTag.vue
  packages/vue/src/components/DetailHeadline/DetailHeadline.stories.js
  packages/vue/src/components/DetailHeadline/DetailHeadline.vue
  packages/vue/src/templates/edu/PageEduEventDetail/PageEduEventDetail.vue
  packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.stories.js
  packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.vue
Labels: bug, patch

#536 fix: header and footer feedback
  packages/common/tailwind.colors.ts
  packages/vue/src/components/NavDesktop/NavDesktopDropdown.vue
  packages/vue/src/components/NavDesktopEdu/NavDesktopEdu.stories.js
  packages/vue/src/components/NavDesktopEdu/NavDesktopEdu.vue
  packages/vue/src/components/NavHeading/NavHeading.stories.js
  packages/vue/src/components/NavHeading/NavHeading.vue
  packages/vue/src/components/NavLinkList/NavLinkList.vue
  packages/vue/src/components/NavMobile/NavMobile.vue
  packages/vue/src/components/TheFooter/TheFooter.vue
Labels: bug, patch

#537 fix: EDU Event Detail Page
  packages/vue/src/components/BaseTag/BaseTag.vue
  packages/vue/src/components/CalendarButton/CalendarButton.vue
  packages/vue/src/components/EventCard/EventCard.vue
  packages/vue/src/components/EventDetailHero/EventDetailHero.vue
  packages/vue/src/templates/PageNewsDetail/PageNewsDetail.vue
  packages/vue/src/templates/edu/PageEduEventDetail/PageEduEventDetail.stories.js
  packages/vue/src/templates/edu/PageEduEventDetail/PageEduEventDetail.vue
  packages/vue/src/utils/mixins.ts
  packages/vue/tsconfig.json
Labels: bug, patch

#538 Feature: Adding boilerplate print styles
  packages/common/src/scss/_print.scss
  packages/common/src/scss/components/_BlockKeyPoints.scss
  packages/common/src/scss/styles.scss
  packages/vue/src/components/BaseButton/BaseButton.vue
  packages/vue/src/components/BaseImage/BaseImage.vue
  packages/vue/src/components/BaseTag/BaseTag.vue
  packages/vue/src/components/BlockIframeEmbed/BlockIframeEmbed.vue
  packages/vue/src/components/BlockImage/BlockImageStandard.vue
  packages/vue/src/components/BlockKeyPoints/BlockKeyPoints.vue
  packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue
  packages/vue/src/components/BlockRelatedLinks/BlockRelatedLinks.vue
  packages/vue/src/components/BlockRelatedLinks/RelatedLink.vue
  packages/vue/src/components/BlockVideo/BlockVideo.vue
  packages/vue/src/components/BlockVideoEmbed/BlockVideoEmbed.vue
  packages/vue/src/components/EventDetailHero/EventDetailHero.vue
  packages/vue/src/components/HeroMedia/HeroMedia.vue
  packages/vue/src/components/MixinCarousel/MixinCarousel.vue
  packages/vue/src/components/NavDesktopEdu/NavDesktopEdu.vue
  packages/vue/src/components/NavMobile/NavMobile.vue
  packages/vue/src/components/ShareButtons/ShareButtons.vue
  packages/vue/src/components/ShareButtonsEdu/ShareButtonsEdu.vue
  packages/vue/src/components/TheFooter/TheFooter.vue
  packages/vue/src/templates/PageEventDetail/PageEventDetail.vue
  packages/vue/src/templates/edu/PageEduEventDetail/PageEduEventDetail.vue
  packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.vue
Labels: patch, feature

#540 fix: minor adjustments to release 3.2.7
  packages/vue/src/components/NavMobile/NavMobile.vue
  packages/vue/src/templates/edu/PageEduEventDetail/PageEduEventDetail.stories.js
  packages/vue/src/utils/mixins.ts
Labels: bug

#541 feature: listing metadata
  packages/common/src/scss/components/_IconProfile.scss
  packages/common/src/scss/components/_IconSubject.scss
  packages/vue/lib/main.ts
  packages/vue/src/components/BasePill/BasePill.stories.js
  packages/vue/src/components/BasePill/BasePill.vue
  packages/vue/src/components/BaseTag/BaseTag.vue
  packages/vue/src/components/BlockLinkCard/BlockLinkCard.stories.js
  packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue
  packages/vue/src/components/BlockLinkCarousel/BlockLinkCarousel.stories.js
  packages/vue/src/components/BlockLinkTile/BlockLinkTile.vue
  packages/vue/src/components/CalendarChip/CalendarChip.vue
  packages/vue/src/components/DetailHeadline/DetailHeadline.vue
  packages/vue/src/components/EventCard/EventCard.vue
  packages/vue/src/components/EventDetailHero/EventDetailHero.vue
  packages/vue/src/components/HeroListingIndex/HeroListingIndex.stories.js
  packages/vue/src/components/HeroListingIndex/HeroListingIndex.vue
  packages/vue/src/components/HeroMedium/HeroMedium.vue
  packages/vue/src/components/Icons/IconProfile.vue
  packages/vue/src/components/Icons/IconSubject.vue
  packages/vue/src/components/Icons/Icons.stories.ts
  packages/vue/src/components/MetadataEduResource/MetadataEduResource.stories.js
  packages/vue/src/components/MetadataEduResource/MetadataEduResource.vue
  packages/vue/src/components/MetadataEvent/MetadataEvent.stories.js
  packages/vue/src/components/MetadataEvent/MetadataEvent.vue
  packages/vue/src/components/SearchResultCard/SearchResultCard.stories.js
  packages/vue/src/components/SearchResultCard/SearchResultCard.vue
  packages/vue/src/components/SearchResultGridItem/SearchResultGridItem.stories.js
  packages/vue/src/components/SearchResultGridItem/SearchResultGridItem.vue
  packages/vue/src/components/SearchResultsList/SearchResultsList.stories.js
  packages/vue/src/components/SearchResultsList/SearchResultsList.vue
  packages/vue/src/components/TopicDetailMoreItem/TopicDetailMoreItem.vue
  packages/vue/src/constants.ts
  packages/vue/src/interfaces.ts
  packages/vue/src/templates/PageContent/PageContent.stories.js
  packages/vue/src/templates/PageEventDetail/PageEventDetail.stories.js
  packages/vue/src/templates/PageEventDetail/PageEventDetail.vue
  packages/vue/src/templates/edu/PageEduEventDetail/PageEduEventDetail.stories.js
  packages/vue/src/templates/edu/PageEduEventDetail/PageEduEventDetail.vue
  packages/vue/src/utils/mixins.ts
  packages/vue/src/utils/rangeifyGrades.ts
Labels: patch, feature

#542 fixing listing page hero images
  packages/vue/src/components/BaseTimer/BaseTimer.vue
  packages/vue/src/components/HeroLarge/HeroLarge.stories.js
  packages/vue/src/components/HomepageCarouselItem/HomepageCarouselItem.stories.js
  packages/vue/src/components/HomepageCarouselItem/HomepageCarouselItem.vue
  packages/vue/src/templates/PageVideoDetail/PageVideoDetail.stories.js
  packages/vue/src/templates/PageVideoDetail/PageVideoDetail.vue
  packages/vue/src/templates/www/PageAsteroidWatchIndex/PageAsteroidWatchIndex.stories.js
  packages/vue/src/templates/www/PageAsteroidWatchIndex/PageAsteroidWatchIndex.vue
  packages/vue/src/templates/www/PageInfographicDetail/PageInfographicDetail.stories.js
  packages/vue/src/templates/www/PageInfographicDetail/PageInfographicDetail.vue
  packages/vue/src/templates/www/PagePodcastSeason/PagePodcastSeason.stories.js
  packages/vue/src/templates/www/PagePodcastSeason/PagePodcastSeason.vue
  packages/vue/src/templates/www/PageRoboticsDetail/PageRoboticsDetail.vue
  packages/vue/src/templates/www/PageTopicDetail/PageTopicDetail.stories.js
  packages/vue/src/templates/www/PageTopicDetail/PageTopicDetail.vue
Labels: bug

#543 Fixing dayjs imports, use composition API in NavSearchForm
  packages/vue/src/components/BaseTimer/BaseTimer.vue
  packages/vue/src/components/NavSearchForm/NavSearchForm.vue
  packages/vue/src/components/PastEventsCarousel/PastEventsCarousel.vue
Labels: bug, patch

#544 Fix/dsn widget
  apps/vue-storybook/.storybook/_mock-components.js
  package.json
  packages/vue/package.json
  packages/vue/src/components/DsnWidget/DsnWidget.vue
  packages/vue/src/components/HomepageStats/HomepageStats.vue
  packages/vue/src/components/PastEventsCarousel/PastEventsCarousel.vue
  packages/vue/src/interfaces.ts
Labels: bug

#545 Fixing BaseTimer
  package.json
  packages/vue/package.json
  packages/vue/src/components/BaseTimer/BaseTimer.vue
  packages/vue/src/utils/dayjs.js
Labels: bug

#546 Fix/reverting dayjs fixes
  package.json
  packages/vue/package.json
  packages/vue/src/components/BaseTimer/BaseTimer.vue
  packages/vue/src/utils/dayjs.js
Labels: bug

#548 feature: MetaPanel, BlockAccordion, EduLessonPage
  apps/vue-storybook/.storybook/preview.ts
  apps/vue-storybook/package.json
  packages/common/src/scss/_grid.scss
  packages/vue/package.json
  packages/vue/src/components/BaseAccordionItem/BaseAccordionItem.stories.js
  packages/vue/src/components/BaseAccordionItem/BaseAccordionItem.vue
  packages/vue/src/components/BaseButton/BaseButton.vue
  packages/vue/src/components/BaseImage/BaseImage.vue
  packages/vue/src/components/BaseImagePlaceholder/BaseImagePlaceholder.vue
  packages/vue/src/components/BaseLink/BaseLink.vue
  packages/vue/src/components/BlockAccordion/BlockAccordion.stories.js
  packages/vue/src/components/BlockAccordion/BlockAccordion.vue
  packages/vue/src/components/BlockHeading/BlockHeading.stories.js
  packages/vue/src/components/BlockHeading/BlockHeading.vue
  packages/vue/src/components/BlockLinkCarousel/BlockLinkCarousel.vue
  packages/vue/src/components/BlockRelatedLinks/RelatedLink.vue
  packages/vue/src/components/BlockStreamfield/BlockStreamfield.stories.js
  packages/vue/src/components/BlockStreamfield/BlockStreamfield.vue
  packages/vue/src/components/BlockText/BlockText.vue
  packages/vue/src/components/HeroMedia/HeroMedia.vue
  packages/vue/src/components/LayoutHelper/LayoutHelper.vue
  packages/vue/src/components/MetaPanel/MetaPanel.stories.js
  packages/vue/src/components/MetaPanel/MetaPanel.vue
  packages/vue/src/components/MetaPanelAccordion/MetaPanelAccordion.vue
  packages/vue/src/components/MetaPanelItems/MetaPanelItems.stories.js
  packages/vue/src/components/MetaPanelItems/MetaPanelItems.vue
  packages/vue/src/components/MetadataEduResource/MetadataEduResource.stories.js
  packages/vue/src/components/MixinCarousel/MixinCarousel.vue
  packages/vue/src/components/NavJumpMenu/NavJumpMenu.vue
  packages/vue/src/components/NavSecondary/NavSecondary.vue
  packages/vue/src/components/ShareButtonsEdu/ShareButtonsEdu.vue
  packages/vue/src/interfaces.ts
  packages/vue/src/main.ts
  packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.stories.js
  packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.vue
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.stories.js
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue
  packages/vue/src/templates/edu/PageEduLesson/PageEduLessonSection.vue
  packages/vue/src/templates/edu/PageEduNewsDetail/PageEduNewsDetail.stories.js
  packages/vue/src/templates/edu/PageEduNewsDetail/PageEduNewsDetail.vue
  packages/vue/src/utils/getHeadingId.ts
  pnpm-lock.yaml
Labels: patch, feature

#547 feature: GitHub gist embed block
  packages/vue/src/components/BlockGist/BlockGist.stories.js
  packages/vue/src/components/BlockGist/BlockGist.vue
  packages/vue/src/components/BlockGist/GitHub404.vue
  packages/vue/src/components/BlockStreamfield/BlockStreamfield.vue
Labels: feature request, feature

#550 fix: MetaPanel adjustments
  packages/common/src/scss/_grid.scss
  packages/vue/src/components/BaseButton/BaseButton.vue
  packages/vue/src/components/MetaPanel/MetaPanel.stories.js
  packages/vue/src/components/MetaPanelAccordion/MetaPanelAccordion.vue
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.stories.js
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue
Labels: patch

#552 fix: event detail page when there are no times, remove ics button for ongoing events
  packages/vue/src/components/CalendarButton/CalendarButton.vue
  packages/vue/src/components/MetadataEvent/MetadataEvent.vue
  packages/vue/src/templates/edu/PageEduEventDetail/PageEduEventDetail.stories.js
  packages/vue/src/templates/edu/PageEduEventDetail/PageEduEventDetail.vue
  packages/vue/src/utils/dayjs.js
  packages/vue/src/utils/rangeifyGrades.ts
Labels: bug, patch

#554 moving BaseTimer dayjs config to main dayjs config
  packages/vue/src/components/BaseTimer/BaseTimer.vue
  packages/vue/src/utils/dayjs.js
Labels: bug

#555 fix: EDU Explainer Article and Header/Footer alignment
  packages/vue/src/components/BaseImageCaption/BaseImageCaption.vue
  packages/vue/src/components/BlockCardGrid/BlockCardGrid.vue
  packages/vue/src/components/BlockGist/BlockGist.stories.js
  packages/vue/src/components/BlockGist/BlockGist.vue
  packages/vue/src/components/BlockStreamfield/BlockStreamfield.stories.js
  packages/vue/src/components/BlockStreamfield/BlockStreamfield.vue
  packages/vue/src/components/BlockTeaser/BlockTeaser.vue
  packages/vue/src/components/NavDesktop/NavDesktop.stories.js
  packages/vue/src/components/NavHeading/NavHeading.vue
  packages/vue/src/components/NavLinkList/NavLinkList.stories.js
  packages/vue/src/components/TheFooter/TheFooter.vue
  packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.stories.js
  packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.vue
Labels: bug, patch

#556 fix: adjustments to NavJumpMenu
  .github/workflows/storybook.yml
  packages/vue/src/components/NavJumpMenu/NavJumpMenu.vue
  packages/vue/src/components/NavSecondary/NavSecondaryDropdown.vue
  packages/vue/src/components/NavSecondary/NavSecondaryLink.vue
  packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.vue
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue
  packages/vue/src/templates/edu/PageEduNewsDetail/PageEduNewsDetail.vue
Labels: bug

#557 feature: BlockAccordion
  packages/vue/src/components/BaseAccordionItem/BaseAccordionItem.vue
  packages/vue/src/components/BlockAccordion/BlockAccordion.stories.js
  packages/vue/src/components/BlockAccordion/BlockAccordion.vue
  packages/vue/src/components/BlockStreamfield/BlockStreamfield.stories.js
  packages/vue/src/components/BlockStreamfield/BlockStreamfield.vue
Labels: feature

#558 adding math text styles, using primary color for BlockText lists
  packages/common/src/scss/_typography.scss
  packages/common/src/scss/components/_BlockText.scss
  packages/common/tailwind.config.ts
  packages/vue/src/docs/foundation/typography.stories.js
Labels: bug

#559 feature: add BlockLinkCardList and BlockLinkCarousel to BlockStreamfield
  packages/vue/src/components/BlockLinkCardList/BlockLinkCardList.stories.js
  packages/vue/src/components/BlockLinkCardList/BlockLinkCardList.vue
  packages/vue/src/components/BlockStreamfield/BlockStreamfield.vue
  packages/vue/src/components/MetadataEduResource/MetadataEduResource.stories.js
  packages/vue/src/components/MetadataEduResource/MetadataEduResource.vue
  packages/vue/src/components/SearchSelectMenu/SearchSelectMenu.vue
  packages/vue/src/interfaces.ts
  packages/vue/src/utils/rangeifyGrades.ts
Labels: feature

#560 feature: PageEduTeachableMoment template
  packages/common/src/scss/_grid.scss
  packages/vue/src/constants.ts
  packages/vue/src/interfaces.ts
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.stories.js
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue
  packages/vue/src/templates/edu/PageEduNewsDetail/PageEduNewsDetail.vue
  packages/vue/src/templates/edu/PageEduTeachableMoment/PageEduTeachableMoment.stories.js
  packages/vue/src/templates/edu/PageEduTeachableMoment/PageEduTeachableMoment.vue
Labels: feature

#567 adding PageEduCollectionsDetail and HeroInlineMedia
  packages/vue/src/components/BasePill/BasePill.vue
  packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue
  packages/vue/src/components/HeroInlineMedia/HeroInlineMedia.vue
  packages/vue/src/components/HeroLarge/HeroLarge.vue
  packages/vue/src/components/HeroMedium/HeroMedium.vue
  packages/vue/src/components/MetaPanel/MetaPanel.vue
  packages/vue/src/components/MetaPanelItems/MetaPanelItems.vue
  packages/vue/src/constants.ts
  packages/vue/src/interfaces.ts
  packages/vue/src/templates/edu/PageEduCollectionsDetail/PageEduCollectionsDetail.stories.js
  packages/vue/src/templates/edu/PageEduCollectionsDetail/PageEduCollectionsDetail.vue
  packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.vue
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue
  packages/vue/src/templates/edu/PageEduTeachableMoment/PageEduTeachableMoment.vue
  packages/vue/src/templates/www/PageRoboticsDetail/PageRoboticsDetail.vue
  packages/vue/src/templates/www/PageTopicDetail/PageTopicDetail.vue
Labels: feature

#569 feature: adding AboutTheAuthor component, and adding to relevant templates
  packages/common/src/scss/components/_BlockText.scss
  packages/vue/src/components/AboutTheAuthor/AboutTheAuthor.stories.js
  packages/vue/src/components/AboutTheAuthor/AboutTheAuthor.vue
  packages/vue/src/components/BlockText/BlockText.vue
  packages/vue/src/components/DetailHeadline/DetailHeadline.vue
  packages/vue/src/interfaces.ts
  packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.stories.js
  packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.vue
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.stories.js
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue
  packages/vue/src/templates/edu/PageEduNewsDetail/PageEduNewsDetail.stories.js
  packages/vue/src/templates/edu/PageEduNewsDetail/PageEduNewsDetail.vue
  packages/vue/src/templates/edu/PageEduTeachableMoment/PageEduTeachableMoment.stories.js
  packages/vue/src/templates/edu/PageEduTeachableMoment/PageEduTeachableMoment.vue
Labels: feature

#570 qa fixes to MetaPanel
  packages/vue/src/components/MetaPanel/MetaPanel.stories.js
  packages/vue/src/components/MetaPanel/MetaPanel.vue
  packages/vue/src/components/MetaPanelItems/MetaPanelItems.vue
  packages/vue/src/utils/rangeifyGrades.ts
Labels: bug, patch

#571 fixing alignment of BlockCardGrid in streamfields
  packages/vue/src/components/BlockCardGrid/BlockCardGrid.vue
  packages/vue/src/components/BlockStreamfield/BlockStreamfield.vue
  packages/vue/src/templates/www/PageRoboticsDetail/PageRoboticsDetail.vue
Labels: bug

#573 fix: ICS for events with no time
  packages/vue/src/components/CalendarButton/CalendarButton.vue
  packages/vue/src/utils/dayjs.js
Labels: bug

#574 fixes: BlockLinkCardList and Card metadata
  packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue
  packages/vue/src/components/BlockStreamfield/BlockStreamfield.vue
  packages/vue/src/components/MetadataEduResource/MetadataEduResource.vue
  packages/vue/src/components/MetadataEvent/MetadataEvent.stories.js
Labels: bug, patch

#575 Fixing feedback on Teachable Moments template
  packages/vue/src/components/AboutTheAuthor/AboutTheAuthor.vue
  packages/vue/src/interfaces.ts
  packages/vue/src/templates/edu/PageEduCollectionsDetail/PageEduCollectionsDetail.vue
  packages/vue/src/templates/edu/PageEduExplainerArticle/PageEduExplainerArticle.vue
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue
  packages/vue/src/templates/edu/PageEduNewsDetail/PageEduNewsDetail.vue
  packages/vue/src/templates/edu/PageEduTeachableMoment/PageEduTeachableMoment.stories.js
  packages/vue/src/templates/edu/PageEduTeachableMoment/PageEduTeachableMoment.vue
Labels: bug, patch

#576 fixes: collection detail page
  packages/vue/src/templates/edu/PageEduCollectionsDetail/PageEduCollectionsDetail.stories.js
  packages/vue/src/templates/edu/PageEduCollectionsDetail/PageEduCollectionsDetail.vue
Labels: bug, patch

#577 nav: fixing active section logic, fixing global nav breadcrumbs interfering with JumpNav
  packages/vue/src/components/NavDesktop/NavDesktop.vue
  packages/vue/src/components/NavJumpMenu/NavJumpMenu.vue
  packages/vue/src/components/NavSecondary/NavSecondary.vue
  packages/vue/src/utils/mixins.ts
Labels: bug

#579 revising data model for EDU Lesson procedures
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.stories.js
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue
  packages/vue/src/templates/edu/PageEduLesson/PageEduLessonSection.vue
Labels: feature

#580 QA fixes for EDU Lesson Page
  packages/common/src/scss/components/_BlockText.scss
  packages/vue/src/components/BlockHeading/BlockHeading.vue
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.stories.js
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.vue
  packages/vue/src/utils/mixins.ts
Labels: bug

#581 removing some stray console.log outputs
  packages/vue/src/components/BlockDialog/BlockDialog.vue
  packages/vue/src/components/NavDesktop/NavDesktop.vue
  packages/vue/src/components/NavSearchForm/NavSearchForm.vue
Labels: maintenance

#582 disabling dark background in iframe embeds for EDU
  packages/vue/src/components/BlockIframeEmbed/BlockIframeEmbed.vue
Labels: bug

#578 fix: migrate contact form back to google endpoint, works in storybook
  packages/vue/src/components/FormContact/FormContact.vue
Labels: bug, storybook

#583 feature: EDU Multimedia and Gallery templates
  packages/vue/src/components/BlockStreamfield/BlockStreamfield.vue
  packages/vue/src/components/NavSecondary/NavSecondaryDropdown.vue
  packages/vue/src/constants.ts
  packages/vue/src/templates/edu/PageEduGalleryDetail/PageEduGalleryDetail.stories.js
  packages/vue/src/templates/edu/PageEduGalleryDetail/PageEduGalleryDetail.vue
  packages/vue/src/templates/edu/PageEduLesson/PageEduLesson.stories.js
  packages/vue/src/templates/edu/PageEduLesson/PageEduLessonSection.vue
  packages/vue/src/templates/edu/PageEduMultimediaDetail/PageEduMultimediaDetail.stories.js
  packages/vue/src/templates/edu/PageEduMultimediaDetail/PageEduMultimediaDetail.vue
  packages/vue/src/utils/getHeadingId.ts
Labels: feature

#584 fixing minor issues on multimedia templates
  packages/vue/src/templates/edu/PageEduGalleryDetail/PageEduGalleryDetail.vue
  packages/vue/src/templates/edu/PageEduMultimediaDetail/PageEduMultimediaDetail.vue
Labels: bug, patch

#585 adding mapping for edu events and elastic search
  packages/vue/src/components/BasePill/BasePill.vue
  packages/vue/src/components/BlockLinkCard/BlockLinkCard.vue
  packages/vue/src/components/BlockLinkCardList/BlockLinkCardList.vue
  packages/vue/src/components/DetailHeadline/DetailHeadline.vue
  packages/vue/src/components/HeroLarge/HeroLarge.vue
  packages/vue/src/components/HeroMedium/HeroMedium.vue
  packages/vue/src/components/SearchResultCard/SearchResultCard.vue
  packages/vue/src/components/SearchResultsList/SearchResultsList.vue
  packages/vue/src/constants.ts
  packages/vue/src/interfaces.ts
  packages/vue/src/templates/edu/PageEduEventDetail/PageEduEventDetail.vue
Labels: feature

#586 Cleans up logic for switching between different content type aliases, adds EDU Search keys
  packages/vue/src/components/SearchFilterGroup/SearchFilterGroup.vue
  packages/vue/src/components/SearchResultCard/SearchResultCard.vue
  packages/vue/src/components/SearchResultGridItem/SearchResultGridItem.vue
  packages/vue/src/constants.ts
  packages/vue/src/utils/lookupContentType.ts
Labels: feature

#587 cleaning up search filter names between EDU and WWW
  packages/vue/src/components/SearchFilterGroup/SearchFilterGroup.vue
  packages/vue/src/constants.ts
Labels: feature
